name: CI

env:
  ELIXIR_VERSION: "1.15"
  OTP_VERSION: "26"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Elixir tests
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}
      - name: Restore dependencies and build cache
        uses: actions/cache@v3
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-otp-${{ steps.beam.outputs.otp-version }}-elixir-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-otp-${{ steps.beam.outputs.otp-version }}-elixir-${{ steps.beam.outputs.elixir-version }}-
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Hex Audit
        run: mix hex.audit
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Run Formatter
        run: mix format --check-formatted
      - name: Run Linter
        run: mix credo
      - name: Run Tests
        run: mix coveralls.json
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./cover/excoveralls.json
